# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-31 12:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import time


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=63)),
                ('content', models.TextField()),
                ('bounty', models.PositiveIntegerField(default=0)),
                ('created_at', models.FloatField(default=time.time)),
                ('cycle', models.FloatField(default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='published_tasks', to=settings.AUTH_USER_MODEL)),
                ('members', models.ManyToManyField(related_name='participated_tasks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
