# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-31 13:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('recruit', '\u62db\u52df\u4e2d'), ('processing', '\u8fdb\u884c\u4e2d'), ('finished', '\u7ed3\u675f')], default=1, max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='task',
            name='bounty',
            field=models.PositiveIntegerField(default=0, verbose_name='\u62a5\u916c'),
        ),
        migrations.AlterField(
            model_name='task',
            name='cycle',
            field=models.FloatField(default=0, verbose_name='\u4efb\u52a1\u5468\u671f'),
        ),
        migrations.AlterField(
            model_name='task',
            name='members',
            field=models.ManyToManyField(null=True, related_name='participated_tasks', to=settings.AUTH_USER_MODEL),
        ),
    ]
