# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-31 13:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20170531_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='members',
            field=models.ManyToManyField(blank=True, null=True, related_name='participated_tasks', to=settings.AUTH_USER_MODEL),
        ),
    ]
